### PR TITLE
get_clusters fix

### PR DESCRIPTION
**Pull request by finlaycampbell**
See #107

### CODE REVIEW

**Comment by zkamvar** [comment]
@finlaycampbell, can you explain what's happening here and maybe write a test for this?

**Comment by finlaycampbell** [comment]
The output from igraph in the command below was coercing case IDs to character: 
https://github.com/reconhub/epicontacts/blob/7f5f401dc3e33a8413c270d1faefe7f44eed567e/R/get_clusters.R#L90-L93
This caused an error when trying to `full_join` this with linelist case IDs, if these were not characters. The fix coerces the igraph output IDs to whatever class the linelist case IDs are. I've added some tests that try `get_clusters` on IDs with different classes.

**Comment by zkamvar** [comment]
> The output from igraph in the command below was coercing case IDs to character:
> 
> https://github.com/reconhub/epicontacts/blob/7f5f401dc3e33a8413c270d1faefe7f44eed567e/R/get_clusters.R#L90-L93
> 
> This caused an error when trying to `full_join` this with linelist case IDs, if these were not characters. The fix coerces the igraph output IDs to whatever class the linelist case IDs are. I've added some tests that try `get_clusters` on IDs with different classes.

Can you add a test that checks if the input is a factor?

**Comment by finlaycampbell** [comment]
Done

**Comment by zkamvar** [comment]
This is failing on push, which might mean that this fix is affecting the new tests added in 7f5f401dc3e33a8413c270d1faefe7f44eed567e. Try merging master into this branch and see how the tests fare.

**Comment by zkamvar** [comment]
Either that, or it means that the tests are failing on this branch because the tests were failing earlier. The PR/push checks really are the USB-socket of checks.

**Comment by finlaycampbell** [comment]
Ah didn't realise I hadn't merged the master branch fixes - hopefully working now. I also had to update one of the reference rds files because it seemed to have been created using an older version of outbreaks.

**Comment by zkamvar** [comment]
> Ah didn't realise I hadn't merged the master branch fixes - hopefully working now. I also had to update one of the reference rds files because it seemed to have been created using an older version of outbreaks.

In general, I'm against changing these tests because it's difficult to asses exactly what has changed, but IIRC, that particular test doesn't actually run anywhere but on a local machine (see #88), so it's all good.

**Comment by finlaycampbell** [comment]
> In general, I'm against changing these tests because it's difficult to asses exactly what has changed, but IIRC, that particular test doesn't actually run anywhere but on a local machine (see #88), so it's all good.

Yeah agreed - generally I'm not sure how good of an idea referencing saved objects is.

**Comment by zkamvar** [comment]
> Yeah agreed - generally I'm not sure how good of an idea referencing saved objects is.

[narrator] It wasn't a good idea.

**Pull request merged**
